// ⚠️ 本文件由 scripts/gen-achievements.ts 自动生成，请勿手改。
// 要改成就数据，请改 docs/achievements.tsv（唯一数据源），然后跑 npm run gen:achievements。

export type AchievementSeed = {
  /** 角色名，如 通用 / 厨师 / 麻脸巫婆 */
  role: string;
  /** 成就名称，数据库里是唯一键 */
  name: string;
  /** 达成条件 */
  condition: string;
  /** 稀有度四档：common / rare / epic / legendary（由 TSV 的星数换算） */
  rarity: string;
  /** 首次达成日期 YYYY-MM-DD */
  firstDate: string | null;
  /** 日期不详时的说明，如「已不可考」 */
  firstDateNote: string | null;
  /** 首位达成者昵称 */
  firstPlayer: string | null;
};

export const ACHIEVEMENT_SEEDS: readonly AchievementSeed[] = [
  {
    role: "通用",
    name: "粘手上了...",
    condition: "连续4局拿到恶魔",
    rarity: "legendary",
    firstDate: "2025-11-29",
    firstDateNote: null,
    firstPlayer: "恶魔哥",
  },
  {
    role: "通用",
    name: "“无恶不做”",
    condition: "拿到过所有恶魔角色",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "恶魔哥",
  },
  {
    role: "通用",
    name: "我是疯子？",
    condition: "作为恶魔，公开表示自己是疯子",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "通用",
    name: "完美犯罪",
    condition: "作为恶魔，从未被怀疑并获得游戏胜利",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "通用",
    name: "踽踽独狼",
    condition: "作为恶魔，爪牙全部死亡的情况下继续存活3天以上并获胜",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "通用",
    name: "路易十六",
    condition: "作为恶魔，在第一个白天被精神病砍死（真是叫人摸不着头脑）",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "清扬",
  },
  {
    role: "通用",
    name: "不可能，绝对不可能！",
    condition: "作为善良玩家，公开保护恶魔直到游戏结束",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "通用",
    name: "错的不是我而是这个世界",
    condition: "作为善良玩家，找到恶魔但几乎无人相信",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "通用",
    name: "这合理吗？",
    condition: "在一局游戏中改变了三次阵营/角色",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "厨师",
    name: "庖丁解牛",
    condition: "作为厨师，首夜得知“3”的正确信息并找到四名邪恶玩家",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "贵族",
    name: "城堡里的三头犬",
    condition: "作为贵族，发现自己在首夜得知了3名邪恶玩家",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "贵族",
    name: "都是忠臣，没有奸臣！",
    condition: "作为贵族，发现自己在首夜得知了3名善良玩家",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "贵族",
    name: "火眼金睛",
    condition: "作为贵族，在第一个白天提名并处决贵族圈里的邪恶玩家",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "共情者",
    name: "夹心饼干",
    condition: "作为共情者，发现自己两边都坐着邪恶玩家",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "舞蛇人",
    name: "蛇舞",
    condition: "作为舞蛇人，在首个夜晚舞到了恶魔",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "舞蛇人",
    name: "俄罗斯轮盘赌",
    condition: "作为舞蛇人，在每个夜晚都选择不同玩家但从未选中恶魔",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "舞蛇人",
    name: "蛇皮走位",
    condition: "作为舞蛇人，成为恶魔后活到游戏结束",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "数学家",
    name: "算术大师",
    condition: "作为数学家，正确推理出每一晚的玩家和角色",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "僧侣",
    name: "慈悲为怀",
    condition: "作为僧侣，连续三天守护了恶魔的目标玩家",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "僧侣",
    name: "盲僧",
    condition: "作为僧侣，连续三天守护了红方玩家",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "荷鲁斯",
  },
  {
    role: "僧侣",
    name: "贫僧也略懂些拳脚",
    condition: "作为僧侣，在从未守护正确的情况下提名并处决恶魔",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "赌徒",
    name: "戒赌宣传大使",
    condition: "作为赌徒，在第一次猜测就把自己赌死",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "赌徒",
    name: "什么是戒赌？",
    condition: "作为赌徒，连续三局在第一次猜测把自己赌死",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "赌徒",
    name: "赌神",
    condition: "作为赌徒，每天选择不同角色猜测且全部正确",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "赌徒",
    name: "命运的硬币",
    condition: "作为赌徒，在炼金术士与爪牙之中猜到正确角色",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "半兽人",
    name: "半兽神",
    condition: "作为半兽人，支配每晚死亡，使恶魔从未能成功杀人",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "半兽人",
    name: "这对吗？",
    condition: "作为半兽人，每晚都选择了邪恶玩家",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "女裁缝",
    name: "牵“红”线",
    condition: "作为女裁缝，选中两名邪恶玩家",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "哲学家",
    name: "借尸还魂",
    condition: "作为哲学家，选择一个已死亡角色的能力，并帮助善良阵营获胜",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "炼金术士",
    name: "以彼之道，还之彼身",
    condition: "作为炼金术士，用爪牙能力帮助善良阵营获胜",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "农夫",
    name: "农夫三拳",
    condition: "作为农夫，将3名善良玩家变成农夫",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "农夫",
    name: "农民起义",
    condition: "作为农夫，在一局游戏中出现至少3名农夫并获得游戏胜利",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "管家",
    name: "忠心不二",
    condition: "作为管家，从始至终都选择同一个主人",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "管家",
    name: "大哥说的对！",
    condition: "作为管家，跟随主人的投票处决恶魔",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "解谜大师",
    name: "回答正确！",
    condition: "作为解谜大师，解谜正确并说服大家处决恶魔",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "解谜大师",
    name: "解谜大宗师",
    condition: "作为解谜大师，连续三局解谜正确",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "疯子",
    name: "飞越疯人院",
    condition: "作为疯子，发现自己是疯子并找到真正的恶魔",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "疯子",
    name: "我是恶魔！",
    condition: "作为疯子，在游戏结束时仍然认为自己是恶魔",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "疯子",
    name: "坏了，我成替身了",
    condition: "作为疯子，坚信自己是恶魔，并帮助善良阵营处决真正的恶魔",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "食人魔",
    name: "我想做个好人",
    condition: "作为食人魔，转变为邪恶但始终认为自己是善良玩家",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "麻脸巫婆",
    name: "我是来退出这个队伍的",
    condition: "作为麻脸，把自己熬成镇民角色",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "麻脸巫婆",
    name: "捣蛋鬼",
    condition: "作为麻脸，在一局游戏中改变三名不同玩家的角色",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "麻脸巫婆",
    name: "谋权篡位",
    condition: "作为麻脸，把自己熬成恶魔并导致原生恶魔死亡",
    rarity: "common",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "麻脸巫婆",
    name: "计划通",
    condition: "作为麻脸，把一名镇民熬成外来者并让方古传刀",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "魔鬼代言人",
    name: "我先休息一会儿！",
    condition: "作为魔代，从未成功保护过玩家",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "魔鬼代言人",
    name: "地狱拯救",
    condition: "作为魔代，连续两次保护玩家免于处决",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "鹰身女妖",
    name: "鹰身恩仇录",
    condition: "作为鹰身女妖，在一局游戏中始终选择同一对玩家",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "鹰身女妖",
    name: "请陛下上马！",
    condition: "作为鹰身女妖，连续选择三次恶魔",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "鹰身女妖",
    name: "死亡三重奏",
    condition: "作为鹰身女妖，在一局游戏中导致3名玩家死亡",
    rarity: "epic",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "哥布林",
    name: "我真的是哥布林",
    condition: "作为哥布林，让大家相信自己是恶魔并通过被处决获得游戏胜利",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "痢蛭",
    name: "倒霉蛋",
    condition: "作为痢蛭，在第一个白天宿主就被处决",
    rarity: "common",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "枫染柒萋",
  },
  {
    role: "痢蛭",
    name: "演得太像也不好...",
    condition: "作为痢蛭，从未被怀疑但是宿主被当作恶魔处决",
    rarity: "rare",
    firstDate: null,
    firstDateNote: null,
    firstPlayer: null,
  },
  {
    role: "精神病患者",
    name: "倒反天罡",
    condition: "作为精神病，在第一个白天杀死魔像",
    rarity: "rare",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "厄运花车",
  },
  {
    role: "精神病患者",
    name: "我一看你就不像恶魔",
    condition: "作为精神病，在第一个白天杀死恶魔",
    rarity: "legendary",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "Frank",
  },
  {
    role: "精神病患者",
    name: "出院！",
    condition: "作为精神病，从不发动能力直到游戏结束",
    rarity: "rare",
    firstDate: null,
    firstDateNote: "已不可考",
    firstPlayer: "恶魔哥",
  },
];
